# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
sphinx:
  configuration: source/conf.py
  
formats:
  - pdf
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: requirements.txt